# https://github.com/marketplace/actions/github-tag-bump

name: Bump version
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: "2.0.3"
          WITH_V: false
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master,main,dev"
